### ISSUE TITLE
InitialState is null in App.razor OnInitializedAsync Method

### ISSUE THREAD

**Issue by COBowler300** [grantcolley/blazor-auth0#1]
Hi,

Thanks for the great example!  I'm very close to getting this working but running across an issue where the InitialState is null in the App.razor when I start the app.  I am using the BlazorServer App.   I do initialize the InitialApplicationState class in the _Host.cshtml and the access token is populated when the app starts.  However, when it gets to the OnInitializedAsync method in the App.razor, InitialState is null because it is not instantiated (object reference not set to an instance of an object error).  Am I missing an instantiation somewhere?

Thanks!

**Comment by COBowler300** [comment]
Oops, forgot to add the param-InitialState="initialState" on the component.  Works great now!

**Comment by grantcolley** [comment]
Thanks @COBowler300. I am glad you got it working.
